[package]
name = "danxi-next"
version = "0.1.1"
description = "A maintainable web and desktop client for DanXi"
authors = ["DanXi Next Contributors"]
edition = "2024"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "danxi_next_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aes-gcm = "0.10"
base64 = "0.22"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
danxi-core = { path = "../crates/danxi-core" }
dotenvy = "0.15"
rand_core = { version = "0.6", features = ["getrandom"] }
tokio = { version = "1", features = ["macros", "sync"] }
